server.port: 8100

spring:
    application:
        name: bankrupt-api
    main:
        allow-bean-definition-overriding: true
    jpa:
        database: postgresql
        ddl-auto: validate
        properties.hibernate.format_sql: true

sync:
    enabled: true
    # 1000ms * 60 * 60 = 1hour
    fixed-delay: 3600000